# Custom Language File for Launcher Customizer

[ejs.app]
title = "Moca Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/hightechnyangtoml/MocaLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/mU8f9rpgcc"

[ejs.settings]
sourceGithubLink = "https://github.com/hightechnyangtoml/MocaLauncher"
supportLink = "https://github.com/hightechnyangtoml/MocaLauncher/issues"

[ejs.welcome]
welcomeHeader = "환영합니다!"
welcomeDescription = "서버가 기다리고 있어요."
welcomeDescCTA = "어서 들어가보아요!"
